### PR TITLE
Add the ability to shift a Line/Span

### PR DESCRIPTION
**Pull request by npmccallum**
This implements the Add/Sub operators for both Line and Span using their
inner types. This means you can shift a Line or Span using simple
addition or subtraction.

Signed-off-by: Nathaniel McCallum <nathaniel@congru.us>

### CODE REVIEW

**Comment by wgwoods** [comment]
1. Aw, no unit tests? :(
2. I feel like there's some ambiguity about whether `span + 3` means "grow the span by 3 units" or "move the span 3 units right". Maybe `+` and `-` should be grow/shrink and the shift operators (`<<` / `>>`) should be shift left/right?

**Review by wgwoods — CHANGES_REQUESTED** [review]
1. give the operations named methods so users can make the intent explicit (grow/shrink vs. shift_l/shift_r)
2. implement `>>` and `<<` operators for shifts
3. add some unit tests for the new operations

**Comment by npmccallum** [comment]
> 1. give the operations named methods so users can make the intent explicit (grow/shrink vs. shift_l/shift_r)

I elected not to do this one since this since I also now implement `*Assign` in addition. This would be 8 duplicate methods on each type, which almost doubled the size of the crate. So it seemed like a lot of pollution.

> 2. implement `>>` and `<<` operators for shifts

Done

> 3. add some unit tests for the new operations

Done. Also, I added documentation.

**Review by wgwoods — APPROVED** [review]
everything looks glorious to me.

**Pull request merged**
